language: python

python: 2.7

env:
  global:
    # configure pip caches
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=flake8

cache:
  # this needs to be set because we're overriding the default install step
  directories:
    - $HOME/.cache/pip

install:
  # build local wheels for caching
  - pip wheel -r requirements.txt
  - pip wheel tox pytest pytest-cov flake8
  - pip install tox

script:
  - tox

notifications:
  email:
    - team@yesgraph.com
